export const HOW_TO_CARDS = [
  {
    bg: 'url("/images/how-to-bg-1.svg")',
    bgDesktop: 'bg-[url("/images/how-to-bg-1.svg")]',
    title: 'Connect Wallet Use MetaMask or Trust Wallet.',
    subtitle1: 'Network Selection',
    content1: '→ Choose Ethereum (ETH), Base Chain (ETH L2), or Binance Smart Chain (BSC).',
    subtitle2: 'Connect Wallet',
    content2: 'Tap “Connect Wallet” on the presale dashboard.',
    bgColor: 'bg-[#FF9A8E]',
    bgColorBorder: 'bg-[#3E4B92]',
    animation: '/images/how-to-animations/how-animation-3.gif',
    video: '/images/how-to-animations/how-animation-3.webm',
    imgWidth: 'w-[345px]',
    imgHeight: 'h-[254px]',
  },
  {
    bg: 'url("/images/how-to-bg-2.svg")',
    bgDesktop: 'bg-[url("/images/how-to-bg-2.svg")]',
    title: 'Choose Token & Amount Select ETH, USDT, USDC (Ethereum/BSC) or BNB (BSC only).',
    subtitle1: 'Set Your Amount',
    content1: "Enter your desired amount to view how many $NEOP tokens you'll receive.",
    subtitle2: 'Approve Transaction',
    content2: 'For stablecoins (USDT, USDC), approve contract first.',
    bgColor: 'bg-[#F9B523]',
    bgColorBorder: 'bg-[#A2664E]',
    animation: '/images/how-to-animations/how-animation-2.gif',
    video: '/images/how-to-animations/how-animation-2.webm',
    imgWidth: 'w-[202px]',
    imgHeight: 'h-[202px]',
  },
  {
    bg: 'url("/images/how-to-bg-3.svg")',
    bgDesktop: 'bg-[url("/images/how-to-bg-3.svg")]',
    title: 'Connect Wallet Use MetaMask or Trust Wallet.',
    subtitle1: 'Network Selection',
    content1: '→ Choose Ethereum (ETH), Base Chain (ETH L2), or Binance Smart Chain (BSC).',
    subtitle2: 'Connect Wallet',
    content2: 'Tap “Connect Wallet” on the presale dashboard.',
    bgColor: 'bg-[#6B9554]',
    bgColorBorder: 'bg-[#E8B148]',
    video: '/images/how-to-animations/how-animation-1.webm',
    animation: '/images/how-to-animations/how-animation-1.gif',
    imgWidth: 'w-[284px]',
    imgHeight: 'h-[250px]',
  },
];
